[package]
name = "ps-datalake"
version = "0.1.0-13"
edition = "2021"
description = "Encrypted flat storage"
license = "GPL-3.0-or-later"

[dependencies]
parking_lot = "0.12.4"
ps-base64 = "0.1.0-5"
ps-datachunk = "0.1.0-30"
ps-hash = "0.1.0-18"
ps-hkey = "0.1.0-26"
ps-mbuf = "0.1.0-4"
ps-mmap = "0.1.0-12"
ps-str = "0.1.0-2"
serde = { version = "1.0.219", features = ["serde_derive"] }
thiserror = "2.0.16"
toml = "0.9.5"

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3
